### ISSUE TITLE
is qtlua install qt ?

### ISSUE THREAD

**Issue by at0mb0y** [torch/qtlua#16]
hello, 
I'm trying this demo: https://github.com/torch/demos/tree/master/load-data to load picture.
I have this error message : 
/Users/joaquim/torch/install/bin/luajit: /Users/joaquim/torch/install/share/lua/5.1/trepl/init.lua:363: module 'qt' not found:No LuaRocks module found for qt
	no field package.preload['qt']
	no file '/Users/joaquim/.luarocks/share/lua/5.1/qt.lua'
	no file '/Users/joaquim/.luarocks/share/lua/5.1/qt/init.lua'
	no file '/Users/joaquim/torch/install/share/lua/5.1/qt.lua'
	no file '/Users/joaquim/torch/install/share/lua/5.1/qt/init.lua'
	no file './qt.lua'
	no file '/Users/joaquim/torch/install/share/luajit-2.1.0-alpha/qt.lua'
	no file '/usr/local/share/lua/5.1/qt.lua'
	no file '/usr/local/share/lua/5.1/qt/init.lua'
	no file '/Users/joaquim/.luarocks/lib/lua/5.1/qt.so'
	no file '/Users/joaquim/torch/install/lib/lua/5.1/qt.so'
	no file './qt.so'
	no file '/usr/local/lib/lua/5.1/qt.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'
stack traceback:
	[C]: in function 'error'
	/Users/joaquim/torch/install/share/lua/5.1/trepl/init.lua:363: in function 'require'
	/Users/joaquim/torch/install/share/lua/5.1/image/init.lua:1247: in function 'display'
	load-images.lua:78: in main chunk
	[C]: in function 'dofile'
	...quim/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:131: in main chunk
	[C]: at 0x0108af22f0

I have installed qtlua, qttorch but nothing change.
It seems  this part of the code makes problem 
for i = 1,math.min(#files,10) do
   image.display{image=images[i], legend=files[i]}
end

maybe this code is too old and use depreciated function.
so just to know is qt  and qtlua are the same ? (because the code is asking for qt but I can't find any qt lua rocks)
Thanks

**Comment by soumith** [comment]
instead of starting the demo with:
th load-images.lua

use

qlua load-images.lua

**Comment by archenroot** [comment]
very important information!!!
