### ISSUE TITLE
qlua -ide not working

### ISSUE THREAD

**Issue by qassemoquab** [torch/qtlua#20]
This commit : 
https://github.com/torch/qtlua/commit/575f723265cf99e178b9f11bfd97f85755af07d5

leads to :
$ qlua -ide
qlua: ...torch-distro/distro/install/share/lua/5.1/qtide/init.lua:73: attempt to call global 'setup' (a nil value)
stack traceback:
	[C]: in function 'setup'
	...torch-distro/distro/install/share/lua/5.1/qtide/init.lua:73: in function 'start'
	[string " qtide.start()"]:1: in main chunk

https://github.com/torch/qtlua/blob/master/packages/qtide/init.lua#L73
"setup" should be "qtide.setup"
This should fix the issue.

Same issue spotted here : https://github.com/torch/qtlua/blob/master/packages/qtide/init.lua#L180
"pcall(help)" should be "pcall(qtide.help)"
I'm not 100% sure but maybe "help" isn't supposed to be "qtide.help" in all cases (if one decides to override it by loading another "help" function).

Also the same thing may have happened in other files.

@colesbury ?

**Comment by UtkarshTiwari30** [comment]
facing the same issue with newly installed torch and lua while using qlua -ide
torch/install/share/lua/5.1/qtide/init.lua:73: attempt to call global 'setup' (a nil value)

**Comment by soumith** [comment]
fixed via #22 and https://github.com/torch/qtlua/commit/c077ce7b429a1e4d9fc8c96dd7115b06ea8bbe46
