### ISSUE TITLE
Cannot load modules in torch

### ISSUE THREAD

**Issue by shimaalizadeh** [torch/qtlua#25]
I am no longer able to load different modules in torch. It keeps giving this error:
------------------------------------------------------------------------------------------------------------
th> require 'torch'
/Users/shima/torch/install/share/lua/5.1/trepl/init.lua:384: loop or previous error loading module 'torch'
stack traceback:
	[C]: in function 'error'
	/Users/shima/torch/install/share/lua/5.1/trepl/init.lua:384: in function 'require'
	[string "_RESULT={require 'torch'}"]:1: in main chunk
	[C]: in function 'xpcall'
	/Users/shima/torch/install/share/lua/5.1/trepl/init.lua:651: in function 'repl'
	...hima/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:199: in main chunk
	[C]: at 0x010493bbd0
--------------------------------------------------------------------------------------------------------------
Previously, it was working fine, and I was using itorch notebook to run my codes. The itorch shows dead kernel, and when I directly run the code by "th mycode.lua" it gives this error.
I highly appreciate your help with this frustrating problem!

**Comment by soumith** [comment]
Could you post this to our google groups here: https://groups.google.com/forum/#!forum/torch7 , we only use this github issues for bug tracking the torch7 package. We'll happily reply there. Thanks.
