### ISSUE TITLE
Cloning into 'exe/qtlua'... Username for 'https://github.com': 

### ISSUE THREAD

**Issue by huanggengxin** [torch/qtlua#29]
will@Will-Air ~/torch-android/distro $ git submodule update --init --recursive
Cloning into 'exe/qtlua'...
Username for 'https://github.com':

**Comment by huanggengxin** [comment]
This is the first time I meet this
I have try my usename and its password
but

remote: Repository not found.
fatal: repository 'https://github.com/borisfom/qtlua.git/' not found
Clone of 'https://github.com/borisfom/qtlua.git' into submodule path 'exe/qtlua' failed

**Comment by soumith** [comment]
this is a torch-android issue. It is cloning the repo from a borisfom/qtlua , torch/qtlua. Please open an issue there and boris will take a look
