### ISSUE TITLE
luarocks install qtlua on macos Sierra (10.12.6) failed 

### ISSUE THREAD

**Issue by mlee980** [torch/qtlua#42]
just upgraded my mac from 10.11.6 to 10.12.6. qtlua does not seem to work any more. 

luarocks install qtlua
Installing https://raw.githubusercontent.com/torch/rocks/master/qtlua-scm-1.rockspec...
Using https://raw.githubusercontent.com/torch/rocks/master/qtlua-scm-1.rockspec... switching to 'build' mode
Cloning into 'qtlua'...
remote: Counting objects: 169, done.
remote: Compressing objects: 100% (163/163), done.
remote: Total 169 (delta 11), reused 123 (delta 2), pack-reused 0
Receiving objects: 100% (169/169), 364.00 KiB | 13.00 KiB/s, done.
Resolving deltas: 100% (11/11), done.
cmake -E make_directory build && cd build && cmake .. -DCMAKE_BUILD_TYPE=Release -DLUA=/Users/mli/src/torch/install/bin/luajit -DLUA_BINDIR="/Users/mli/src/torch/install/bin" -DLUA_INCDIR="/Users/mli/src/torch/install/include" -DLUA_LIBDIR="/Users/mli/src/torch/install/lib" -DLUADIR="/Users/mli/src/torch/install/lib/luarocks/rocks/qtlua/scm-1/lua" -DLIBDIR="/Users/mli/src/torch/install/lib/luarocks/rocks/qtlua/scm-1/lib" -DCONFDIR="/Users/mli/src/torch/install/lib/luarocks/rocks/qtlua/scm-1/conf" && make

-- The C compiler identification is AppleClang 9.0.0.9000037
-- The CXX compiler identification is AppleClang 9.0.0.9000037
...
...
[ 94%] Building CXX object packages/qtwidget/CMakeFiles/libqtwidget.dir/qtlualistener.cpp.o
/tmp/luarocks_qtlua-scm-1-5894/qtlua/packages/qtwidget/qtlualistener.cpp:25:10: error: ordered comparison between pointer and zero
      ('const QMetaObject *' and 'int')
  if (mo >= 0)
      ~~ ^  ~
1 error generated.
make[2]: *** [packages/qtwidget/CMakeFiles/libqtwidget.dir/qtlualistener.cpp.o] Error 1
make[1]: *** [packages/qtwidget/CMakeFiles/libqtwidget.dir/all] Error 2
make: *** [all] Error 2

Error: Build error: Failed building.

**Comment by gluque** [comment]
Try to fix the problem with: 

`if (mo >= (void *)0 ) {`

**Comment by mlee980** [comment]
thanks.

**Comment by deang46** [comment]
Still broken as of today. macOS High Sierra 10.13.2

**Comment by keineahnung2345** [comment]
Still broken at 2018.4. And @gluque 's suggestion works for me. I use macOS High Sierra 10.13.3.

**Comment by OlivierMorere** [comment]
I have submitted a pull request for this issue 
https://github.com/torch/qtlua/pull/47
