### ISSUE TITLE
isLocalFile member of QUrl does not exist in Qt4.7

### ISSUE THREAD

**Issue by seeocean2000** [torch/qtlua#8]
With Qt4.7, I got the following error:
   ... qtlua/packages/qtcore/qtcore.cpp:551: error: ‘class QUrl’ has no member named ‘isLocalFile’

I believe this member only becomes available in Qt 4.8.

See references below:
https://qt-project.org/doc/qt-4.7/qurl.html
http://qt-project.org/doc/qt-4.8/qurl.html

**Comment by leonbottou** [comment]
Fixed

**Comment by seeocean2000** [comment]
Thanks a lot!

On Tue, Nov 3, 2015 at 3:54 PM, Leon Bottou <notifications@github.com>
wrote:

> Fixed
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/torch/qtlua/issues/8#issuecomment-153527653>.
>



-- 
Yang Chen
GPG ID: F0673B36
